server:
  port: 9090
spring:
  application:
    name: springsecurityexample
  datasource:
    url: jdbc:mysql://localhost:3306/restsecureapidb?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
    show-sql: true

    
#Logger configuration
logging:
  file:
    name: logs/app.log
#The filename pattern used to create log archives.
  logback:
    rollingpolicy:
      file-name-pattern: logs/%d{yyyy-MM, aux}/app.%d{yyyy-MM-dd}.%i.log
#The maximum size of log file before it is archived.
      max-file-size: 100MB
#The maximum amount of size log archives can take before being deleted.
      total-size-cap: 10GB
#The maximum number of archive log files to keep (defaults to 7).
      max-history: 10
    